import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const client = readFileSync(new URL('../src/dsh-adapter/client.tsx', import.meta.url), 'utf8')
const batches = readFileSync(new URL('../src/dsh-adapter/client-batches.tsx', import.meta.url), 'utf8')
const memory = readFileSync(new URL('../src/dsh-adapter/client-memory.tsx', import.meta.url), 'utf8')
const statistics = readFileSync(new URL('../src/dsh-adapter/client-statistics.tsx', import.meta.url), 'utf8')

describe('Novel Studio 0.8 author control client', () => {
  it('adds separate author-control navigation and replaces the decorative growth map with statistics', () => {
    expect(client).toContain('label="批量生成"')
    expect(client).toContain('label="记忆"')
    expect(client).toContain('label="实体关系"')
    expect(client).toContain('label="创作统计"')
    expect(client).toContain('<ChapterBatchesPanel')
    expect(client).toContain('<MemoryBrowserPanel')
    expect(client).toContain('<EntityRelationshipsPanel')
    expect(client).toContain('<ProjectStatisticsPanel')
    expect(client).not.toContain('<StoryGrowthView')
    expect(statistics).toContain('/statistics`')
    expect(statistics).toContain('章节 AI 调用')
    expect(statistics).toContain('已记录 Token')
    expect(statistics).toContain('AI 正文产出')
    expect(statistics).toContain('逐章消耗与产出')
    expect(statistics).toContain('其余不估算')
    expect(statistics).toContain('value.inputTokens + value.outputTokens + value.cacheReadTokens + value.cacheWriteTokens')
    expect(statistics).toContain('@media(max-width:1100px)')
    expect(statistics).not.toContain('<svg')
  })

  it('implements bounded batch creation and explicit high-cost confirmation', () => {
    expect(batches).toContain("type CreateMode = 'selected' | 'continuous'")
    expect(batches).toContain("automationMode === 'yolo' || creation.count >= 10")
    expect(batches).toContain('单批必须为 1—20 章')
    expect(batches).toContain('confirmed: confirmed || undefined')
    expect(batches).toContain('确认计划并创建队列')
    expect(batches).toContain('/approve-plan`')
    expect(batches).toContain('/reorder`')
    expect(batches).toContain('/skip`')
    expect(batches).toContain('完成当前步骤后暂停')
    expect(batches).toContain('YOLO 只代表跳过人工审批，不代表真正质量审校')
    expect(batches).toContain('/relationships/mode`')
    expect(batches).toContain('关系自动提取已关闭')
    expect(batches).toContain('本批次不会自动提取关系候选')
    expect(batches).toContain('前往实体关系')
    expect(batches).not.toContain("disabled={relationshipMode !== 'auto' && relationshipMode !== 'yolo'}")
    expect(batches).not.toContain('yoloRelationshipBlocked')
    expect(client).toContain("onOpenRelationships={() => { setSection('relationships') }}")
    expect(batches).not.toContain('window.confirm')
    expect(batches).not.toContain('window.alert')
  })

  it('presents paused, blocked and cancelled batches without one shared danger state', () => {
    expect(batches).toContain("status === 'blocked' || status === 'awaiting_plan_approval'")
    expect(batches).toContain("if (status === 'planning' || status === 'queued' || status === 'running') return 'active'; return 'idle'")
    expect(batches).toContain("if (item.queueState === 'blocked') return 'warning'")
    expect(batches).toContain("batch.status === 'blocked' ? '批次需要处理' : '批次已暂停'")
    expect(batches).toContain('>重试本章</button>')
    expect(batches).not.toContain('重试失败项')
  })

  it('provides searchable memory facets, immutable history, usage and override editing', () => {
    expect(memory).toContain('全文搜索')
    expect(memory).toContain('存储位置')
    expect(memory).toContain('最近使用')
    expect(memory).toContain('创建作者覆盖')
    expect(memory).toContain('恢复为新版本')
    expect(memory).toContain('使用记录')
    expect(memory).toContain('/diff?from=${encodeURIComponent(compared.id)}&to=${encodeURIComponent(item.currentRevision.id)}')
    expect(memory).toContain('sourceChangeLabel(compared.sources, item.sources)')
    expect(memory).toContain('模型派生记忆')
    expect(memory).toContain('正式 Canon 始终拥有更高权威')
    expect(memory).toContain('/memory/rescan`')
    expect(memory).toContain('/memory/conflicts`')
    expect(memory).toContain('nextCursor')
    expect(memory).toContain('加载更多（剩余')
    expect(memory).toContain('/usages?limit=30')
    expect(memory).toContain('modelRunId: {usage.modelRunId}')
    expect(memory).toContain('sectionKey: {usage.sectionKey')
    expect(memory).toContain('included: {usage.included')
    expect(memory).toContain('truncated: {usage.truncated')
    expect(memory).toContain('tokens: {usage.estimatedTokens}')
    expect(memory).toContain('reason: {usage.reason')
    expect(memory).toContain("resolve(conflict, 'database')")
    expect(memory).toContain("resolve(conflict, 'file')")
    expect(memory).toContain('共同基线')
    expect(memory).toContain('SQLite 当前内容')
    expect(memory).toContain('Markdown 文件内容')
    expect(memory).toContain('aria-label="冲突合并正文"')
    expect(memory).toContain("resolve(conflict, 'merged', mergedContent)")
  })

  it('wires relationship permission, candidate decisions, evidence and manual revisions', () => {
    expect(client).toContain('关系提取权限')
    expect(client).toContain("(['off','auto','yolo'] as RelationshipMode[])")
    expect(client).toContain('/relationships/candidates/${encodeURIComponent(candidateId)}/${action}`')
    expect(client).toContain('/evidence`')
    expect(client).toContain('手工创建 / 修订')
    expect(client).toContain('/revise`')
    expect(client).toContain('候选关系不会')
  })

  it('uses single-column narrow flows and avoids page-level width assumptions', () => {
    expect(batches).toContain('ns-batches__workspace--narrow')
    expect(memory).toContain('ns-memory__workspace--narrow')
    expect(memory).toContain('返回记忆列表')
    expect(batches).toContain('返回批次列表')
    expect(client).toContain("initialMode={narrow ? 'list' : 'graph'}")
    expect(batches).not.toContain('100vw')
    expect(memory).not.toContain('100vw')
  })
})
